### ISSUE TITLE
Materiaalin alku

### ISSUE THREAD

**Issue by J-Leino** [Kum-Fu/Has-Fun#1]
Ollaan keskustelu aiheesta Johnin kanssa jo skypessä, laitetaan myös tänne avoimeks issueks:
- Yleisesti ei ole ihan hirveästi valitettavaa tekstissä, en välttämättä pidä puhuttelevasta sävystä, mutta tämäkin on mielipdekysymys ja tuo sävy pitää tekstin tarpeeksi värikkäänä helposti, aiheet käsitelty hyvin ja melko sopivalla tarkkuudella.

Isoin ongelma mielestäni on tällä hetkellä tekstin rakenne: aivan ensimmäisiä sanoja lukuunottamatta lähdetään rakentamaan hyvinkin täsmällistä mallia ja määritelmää laskennalle ja laskettavuudelle, ja kuten monissa matematiikan asioissa, näkisin, että tässä olisi hyötyä jonkinlaiselle "motivoinnille" seuraavien määritelmien ja rakennelman mielekkyyttä. John jo lisäsi wikiin TODO kappaleen, jonka mielestäni voisi omistaa tälle ajatukselle. 

Itse lähtisin meille (ihmisille, matemaatikoille, käpistelijöille) ainakin jollain tapaa tutusta ja selvästä "laskennan" käsitteestä - selkokielellä, ilman matemaattista täsmällisyyttä, esittelisin tämän ja selittäisin miksi täsmällinen määritelmä on tarpeen, mitä kaikkea haluamme tämän määritelmän sisältävän ja toimivan ja miksi. Pyrkisin sitten liittämään tämän naivin käsitteistön ohjelmointiin. Vasta sitten jatkaisin Johnin jo aloittamalla työllä laskennan täsmällisempään määrittelyyn.

Mielipiteitä, kysymyksiä, ideoita? Kummanlainen rakenne muiden mielestä toimisi paremmin?
(Saatan pyrkiä jo ennen vastauksia aloittelemaan tuota kappaletta, kritiikkiä ajatusta kohtaan saa silti esittää ja mitään ei ole hakattu kiveen vielä)

**Comment by jllang** [comment]
I decided to start over again with the material. It needs to be more rigorous and professional.
